name: url-shortener

services:
  postgres:
    image: postgres:18
    container_name: url-shortener-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1327
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql

  redis:
    image: redis:8
    container_name: url-shortener-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  backend:
    build:
      context: ../../apps/backend
      dockerfile: Dockerfile
    container_name: url-shortener-backend
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://admin:1327@postgres:5432/urlshortener
      REDIS_URL: redis://redis:6379
      PORT: 3001
    env_file:
      - ../../apps/backend/.env
    ports:
      - "3001:3001"
    volumes:
      - ../../apps/backend/src:/app/src
      - ../../apps/backend/package.json:/app/package.json
      - ../../apps/backend/package-lock.json:/app/package-lock.json
      - ../../apps/backend/tsconfig.json:/app/tsconfig.json

  frontend:
    build:
      context: ../../apps/frontend
      dockerfile: Dockerfile
    container_name: url-shortener-frontend
    restart: unless-stopped
    volumes:
      - ../../apps/frontend/src:/app/src
      - ../../apps/frontend/public:/app/public
      - ../../apps/frontend/index.html:/app/index.html
      - ../../apps/frontend/vite.config.ts:/app/vite.config.ts
      - ../../apps/frontend/tsconfig.json:/app/tsconfig.json
      - ../../apps/frontend/tsconfig.app.json:/app/tsconfig.app.json
      - ../../apps/frontend/tsconfig.node.json:/app/tsconfig.node.json
      - ../../apps/frontend/package.json:/app/package.json
      - ../../apps/frontend/package-lock.json:/app/package-lock.json
      - ../../apps/frontend/.env:/app/.env

  nginx:
    image: nginx:alpine
    container_name: url-shortener-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  redis_data:
